### ISSUE TITLE
 I can't get it to work

### ISSUE THREAD

**Issue by mikrotickets** [mjducharme/bulk-netinstall-ui#1]
**I can't get it to work, you could go through the installation steps**

![Screenshot_53](https://user-images.githubusercontent.com/63126121/130499073-4cd6d90f-6641-4451-a349-3b6dfa3bc9d6.png)
![Screenshot_54](https://user-images.githubusercontent.com/63126121/130499076-23aac207-aa96-4d74-ad89-de1a8a7afb09.png)

**Comment by mjducharme** [comment]
I have just started to develop it... you'll have to wait until it is ready
